// display.cpp
// ST7789 240x240 rendering, Adafruit_GFX + Adafruit_ST7789 backed.
//
// Why Adafruit not TFT_eSPI: on this ESP32-S3R8 clone TFT_eSPI's tft.init()
// crashed before any pixel was drawn (verified via boot-loop traces). Adafruit
// gives us explicit control over the SPIClass and SPI mode, which made the
// panel come up cleanly during hardware bring-up.
//
// Layout (vertical, 240x240, all coordinates from config.h):
//   0..27    header   "CC HUD" + connection dot
//   36..107  5H row   label + big percentage + bar + "used / limit"
//   120..191 7D row   same layout
//   210..235 footer   "updated Xm ago" / "stale Xm" / "waiting for data..."
//
// Partial redraw: a LastDrawnState snapshot avoids fillScreen on every tick.
// Only regions whose inputs changed get repainted.

#include "display.h"

#include <Adafruit_GFX.h>
#include <Adafruit_ST7789.h>
#include <SPI.h>
#include <Fonts/FreeSans9pt7b.h>
#include <Fonts/FreeSans12pt7b.h>
#include <Fonts/FreeSansBold12pt7b.h>
#include <Fonts/FreeSansBold24pt7b.h>

#include <cstdio>
#include <cstring>
#include <climits>
#include <cmath>
#include <ctime>

#include "config.h"
#include "claude_star_frames.h"   // generated by tools/generate_star_frames.py
#include "logo_brand.h"           // generated brand logo
#include "tool_icons.h"           // generated tool icons + name→icon map

namespace cc_hud {

namespace {

// Dedicated HSPI bus (SPI2). Leaves FSPI free for any future expansion.
SPIClass        g_spi(HSPI);
Adafruit_ST7789 g_tft(&g_spi, kPinLcdCs, kPinLcdDc, kPinLcdRst);

// Bookkeeping for partial-redraw. INT_MIN / 0xFFFF sentinels force a paint on
// the first render after boot. *_label fields cache the formatted strings so
// we can skip a row repaint when the user-visible text is identical even if
// internal numbers nudged sub-minute.
struct LastDrawnState {
    // Header.
    char     title[33]            = {0};
    bool     header_drawn         = false;
    bool     ble_connected        = false;

    // Subscription-mode body.
    int16_t  pct_5h               = -1;
    uint16_t used_5h              = 0xFFFF;
    uint16_t limit_5h             = 0xFFFF;
    char     reset_label_5h[16]   = {0};
    int16_t  pct_7d               = -1;
    uint16_t used_7d              = 0xFFFF;
    uint16_t limit_7d             = 0xFFFF;
    char     reset_label_7d[16]   = {0};

    // API-mode body.
    uint32_t cost_micro_usd       = 0xFFFFFFFFu;
    uint32_t duration_s           = 0xFFFFFFFFu;

    // Which mode the body region currently holds (so we know to wipe it
    // when the mode flips).
    int8_t   body_mode_drawn      = -1;  // -1 = nothing drawn yet

    // Footer.
    int32_t  footer_stale_min     = INT32_MIN;
    bool     footer_stale_red     = false;
};
LastDrawnState g_last;

// Format the remaining-until-reset seconds into a short label, e.g.
// "" (zero/unknown), "45s", "12m", "4h12m", "5d". Buffer must be >= 8 bytes.
void formatRemaining(uint32_t remaining_s, char* out, size_t out_sz) {
    if (out_sz == 0) return;
    if (remaining_s == 0) {
        out[0] = '\0';
        return;
    }
    if (remaining_s < 60) {
        std::snprintf(out, out_sz, "%us", static_cast<unsigned>(remaining_s));
        return;
    }
    if (remaining_s < 3600) {
        std::snprintf(out, out_sz, "%um", static_cast<unsigned>(remaining_s / 60));
        return;
    }
    if (remaining_s < 86400) {
        const unsigned h = remaining_s / 3600;
        const unsigned m = (remaining_s % 3600) / 60;
        std::snprintf(out, out_sz, "%uh%um", h, m);
        return;
    }
    const unsigned d = remaining_s / 86400;
    const unsigned h = (remaining_s % 86400) / 3600;
    if (h == 0) {
        std::snprintf(out, out_sz, "%ud", d);
    } else {
        std::snprintf(out, out_sz, "%ud%uh", d, h);
    }
}

// Apply the elapsed-since-capture decrement so the countdown stays live
// between BLE pushes. Saturates at 0.
uint32_t liveRemainingS(uint32_t captured_s, uint64_t capture_ms, uint64_t now_ms) {
    if (captured_s == 0) {
        return 0;
    }
    const uint64_t elapsed_ms = (now_ms >= capture_ms) ? (now_ms - capture_ms) : 0;
    const uint32_t elapsed_s  = static_cast<uint32_t>(elapsed_ms / 1000ULL);
    return (elapsed_s >= captured_s) ? 0u : (captured_s - elapsed_s);
}

// ---------------------------------------------------------------- math/utils
uint8_t computePercent(uint16_t used, uint16_t limit) {
    if (limit == 0) {
        return 0;
    }
    const uint32_t pct = (static_cast<uint32_t>(used) * 100u) / limit;
    return pct > 100u ? 100u : static_cast<uint8_t>(pct);
}

uint16_t colorForPct(uint8_t pct) {
    if (pct <= kThreshGreenMax) {
        return kColorGreen;
    }
    if (pct <= kThreshYellowMax) {
        return kColorYellow;
    }
    return kColorRed;
}

// ------------------------------------------------------------------ text --
//
// Adafruit_GFX FreeFonts use the cursor (x, y) as the *baseline*, not the
// top-left. We supply baseline coordinates throughout, and helper wrappers
// compute right-aligned positions via getTextBounds().

void printAt(const char* s,
             int16_t x, int16_t y_baseline,
             uint16_t color,
             const GFXfont* font) {
    g_tft.setFont(font);
    g_tft.setTextColor(color);
    g_tft.setCursor(x, y_baseline);
    g_tft.print(s);
}

void printRight(const char* s,
                int16_t x_right, int16_t y_baseline,
                uint16_t color,
                const GFXfont* font) {
    g_tft.setFont(font);
    g_tft.setTextColor(color);
    int16_t  x1, y1;
    uint16_t w, h;
    g_tft.getTextBounds(s, 0, 0, &x1, &y1, &w, &h);
    g_tft.setCursor(x_right - static_cast<int16_t>(w), y_baseline);
    g_tft.print(s);
}

// ------------------------------------------------------------------ header --
//
// The header bar shows the active plan / subscription level ("Plan Max (20x)",
// "API", "Free", whatever the host writes in the v3 payload). On the right
// there's a small dot indicating BLE connection state.
//
// Long titles are truncated graphically — we don't shrink the font.
void drawHeader(const char* title, bool connected) {
    g_tft.fillRect(0, kHeaderY, kScreenWidth, kHeaderH, kColorBg);

    constexpr int16_t kTitleStartX = kRowMargin;

    // Reserve a strip on the right for the connection dot so the title never
    // overlaps it.
    const int16_t max_title_w = kScreenWidth - kTitleStartX -
                                kHeaderDotPad - (kHeaderDotR * 2) - 4;
    g_tft.setFont(&FreeSansBold12pt7b);
    g_tft.setTextColor(kColorFg);
    g_tft.setCursor(kTitleStartX, kHeaderY + 22);
    // Manually clip to max_title_w using getTextBounds on a growing prefix.
    int16_t  x1, y1;
    uint16_t w, h;
    g_tft.getTextBounds(title, 0, 0, &x1, &y1, &w, &h);
    if (w <= max_title_w) {
        g_tft.print(title);
    } else {
        // Slow path: print char-by-char until we'd exceed max_title_w.
        char buf[2] = {0, 0};
        int16_t cursor_x = kTitleStartX;
        for (const char* p = title; *p; ++p) {
            buf[0] = *p;
            g_tft.getTextBounds(buf, 0, 0, &x1, &y1, &w, &h);
            if (cursor_x + static_cast<int16_t>(w) > kTitleStartX + max_title_w) {
                break;
            }
            g_tft.print(buf);
            cursor_x += static_cast<int16_t>(w);
        }
    }

    const uint16_t dot_color = connected ? kColorDotLink : kColorDotIdle;
    const int16_t  dot_x     = kScreenWidth - kHeaderDotPad - kHeaderDotR;
    const int16_t  dot_y     = kHeaderY + (kHeaderH / 2);
    g_tft.fillCircle(dot_x, dot_y, kHeaderDotR, dot_color);
    g_tft.drawCircle(dot_x, dot_y, kHeaderDotR, kColorFg);
}

void drawHeaderDot(bool connected) {
    const uint16_t dot_color = connected ? kColorDotLink : kColorDotIdle;
    const int16_t  dot_x     = kScreenWidth - kHeaderDotPad - kHeaderDotR;
    const int16_t  dot_y     = kHeaderY + (kHeaderH / 2);
    // Wipe a slightly larger box to avoid ring artefacts before redrawing.
    g_tft.fillRect(dot_x - kHeaderDotR - 2,
                   dot_y - kHeaderDotR - 2,
                   (kHeaderDotR + 2) * 2,
                   (kHeaderDotR + 2) * 2,
                   kColorBg);
    g_tft.fillCircle(dot_x, dot_y, kHeaderDotR, dot_color);
    g_tft.drawCircle(dot_x, dot_y, kHeaderDotR, kColorFg);
}

// --------------------------------------------------------------------- row --
//
// Row vertical structure (row height 72):
//   y+0..y+30   label baseline @ y+22  | percentage baseline @ y+34
//   y+44..y+57  progress bar (kBarHeight=14)
//   y+59..y+71  used/limit small text baseline @ y+72
void drawRow(const char* label,
             const char* reset_label,
             int16_t row_y,
             uint16_t used, uint16_t limit,
             uint8_t pct) {
    g_tft.fillRect(0, row_y, kScreenWidth, k5hRowH, kColorBg);

    const uint16_t color = colorForPct(pct);

    // Label (small bold, top-left).
    printAt(label,
            kRowMargin, row_y + 22,
            kColorMuted, &FreeSansBold12pt7b);

    // Reset countdown next to the label — tiny font, muted color. Only drawn
    // when the host supplied a non-empty string.
    if (reset_label && reset_label[0] != '\0') {
        // Get width of label so we know where to put the countdown.
        g_tft.setFont(&FreeSansBold12pt7b);
        int16_t  x1, y1;
        uint16_t lw, lh;
        g_tft.getTextBounds(label, 0, 0, &x1, &y1, &lw, &lh);
        printAt(reset_label,
                kRowMargin + static_cast<int16_t>(lw) + 8,
                row_y + 22,
                kColorMuted, &FreeSans9pt7b);
    }

    // Big percentage (right-aligned, big bold). Baseline at row_y + 34
    // sits inside the upper half of the row.
    char pct_buf[8];
    std::snprintf(pct_buf, sizeof(pct_buf), "%u%%", static_cast<unsigned>(pct));
    printRight(pct_buf,
               kScreenWidth - kRowMargin, row_y + 36,
               color, &FreeSansBold24pt7b);

    // Progress bar.
    const int16_t bar_x = kBarMarginX;
    const int16_t bar_y = row_y + 44;
    const int16_t bar_w = kScreenWidth - (kBarMarginX * 2);
    g_tft.fillRect(bar_x, bar_y, bar_w, kBarHeight, kColorBarTrack);
    const int16_t fill_w =
        static_cast<int16_t>((static_cast<int32_t>(bar_w) * pct) / 100);
    if (fill_w > 0) {
        g_tft.fillRect(bar_x, bar_y, fill_w, kBarHeight, color);
    }
    g_tft.drawRect(bar_x, bar_y, bar_w, kBarHeight, kColorMuted);

    // "used / limit" under the bar.
    char usage_buf[24];
    std::snprintf(usage_buf, sizeof(usage_buf),
                  "%u / %u",
                  static_cast<unsigned>(used),
                  static_cast<unsigned>(limit));
    printAt(usage_buf,
            bar_x, bar_y + kBarHeight + 14,
            kColorMuted, &FreeSans9pt7b);
}

// API-mode body: big "$X.YZ" cost in the centre and a "t: 1m20s" duration
// below. Replaces the two quota rows when mode == kSnapshotModeApi.
void formatDuration(uint32_t total_s, char* out, size_t out_sz) {
    if (out_sz == 0) return;
    if (total_s >= 3600) {
        const unsigned h = total_s / 3600;
        const unsigned m = (total_s % 3600) / 60;
        std::snprintf(out, out_sz, "%uh%um", h, m);
    } else if (total_s >= 60) {
        const unsigned m = total_s / 60;
        const unsigned s = total_s % 60;
        std::snprintf(out, out_sz, "%um%us", m, s);
    } else {
        std::snprintf(out, out_sz, "%us", static_cast<unsigned>(total_s));
    }
}

// ------------------------------------------------------------------ idle --
//
// Idle body: a centred big clock + date + user-supplied status line. We keep
// last drawn strings in g_last_idle so partial redraws only repaint regions
// whose visible text actually changed (huge win when the 5-second loop tick
// only changes one of clock/date/status).
struct LastDrawnIdle {
    char clock_text[8]  = {0};
    char date_text[24]  = {0};
    char status_text[33] = {0};
    bool initialized   = false;
};
static LastDrawnIdle g_last_idle;

// Layout (idle screen Y coordinates):
constexpr int16_t kIdleClockBaselineY  = 110;
constexpr int16_t kIdleClockRowY       = 65;
constexpr int16_t kIdleClockRowH       = 55;
constexpr int16_t kIdleDateBaselineY   = 150;
constexpr int16_t kIdleDateRowY        = 130;
constexpr int16_t kIdleDateRowH        = 28;
constexpr int16_t kIdleSeparatorY      = 170;
constexpr int16_t kIdleStatusBaselineY = 210;
constexpr int16_t kIdleStatusRowY      = 185;
constexpr int16_t kIdleStatusRowH      = 35;

// Pet sprite (idle screen only). ASCII-art kitty rendered in Claude
// orange, walking randomly across the top of the screen. Two text
// frames swap on blink. Sprite is ~84 px wide × 16 px tall (7 chars at
// textSize=2, default 6×8 font cell → 12×16 px per char).
constexpr int16_t kIdlePetMinX     = 50;
constexpr int16_t kIdlePetMaxX     = kScreenWidth - 50;
constexpr int16_t kIdlePetBaseY    = 28;
constexpr int16_t kIdlePetBobAmpY  = 2;
constexpr int16_t kIdlePetBobMaxY  = kIdlePetBaseY + kIdlePetBobAmpY;
constexpr int16_t kIdlePetHalfW    = 48;     // 7 chars × 12 = 84, half ≈ 42 + padding
constexpr int16_t kIdlePetTopY     = 16;
constexpr int16_t kIdlePetBotY     = kIdlePetBobMaxY + 14;
constexpr uint32_t kIdlePetBlinkPeriodMs   = 4500;
constexpr uint32_t kIdlePetBlinkDurMs      = 250;
constexpr uint32_t kIdlePetBobPeriodMs     = 500;
constexpr uint32_t kIdlePetLegSwapPeriodMs = 280;   // unused but kept for API parity
constexpr uint32_t kIdlePetRetargetMinMs   = 2500;  // random walk: pick new target
constexpr uint32_t kIdlePetRetargetMaxMs   = 5500;

// Claude Code mascot orange (#D77757 → RGB565).
constexpr uint16_t kColorClaude = 0xDBAA;
// Dimmed Claude orange (~28% intensity) for the idle indicator —
// matches the Claude iOS app's "I'm here but resting" look.
constexpr uint16_t kColorClaudeDim = 0x49E2;

// Claude "thinking" splatter star — 12 thick rays from a dense centre,
// each with its own base length (irregular, hand-drawn feel). Subtle
// per-ray length shimmer (~12% amplitude) + slow rotation. Mimics the
// Claude iOS app's idle animation — present but never distracting.
constexpr int16_t kStarCx           = kScreenWidth - 22;  // 218 — nudged left a hair
constexpr int16_t kStarCy           = kFooterY + 2;       // 212 — fits 192..232 in 240
constexpr int16_t kStarCoreRadius   = 3;
constexpr int16_t kStarRayMax       = 14;
constexpr int16_t kStarHalfBbox     = 18;
constexpr int     kStarRayCount     = 12;
constexpr float   kStarRayBaseHalfW = 2.2f;
constexpr uint32_t kStarPulsePeriodMs = 2800;   // slow shimmer
constexpr uint32_t kStarRotPeriodMs   = 9000;   // very slow rotation
constexpr float   kStarShimmerAmp     = 0.12f;  // ±12% length variation
// Per-ray base length ratios — irregular splatter shape.
constexpr float kStarRayLenRatio[12] = {
    1.00f, 0.82f, 0.95f, 0.70f, 1.00f, 0.78f,
    0.92f, 0.72f, 1.00f, 0.85f, 0.88f, 0.68f,
};

// Cached state.
int16_t g_pet_last_x          = -1;
int16_t g_pet_last_y          = -1;
int8_t  g_pet_frame_drawn     = -1;
int8_t  g_pet_last_walk_frame = -1;
int8_t  g_pet_last_mood       = -1;

void drawCentered(const char* s, int16_t baseline_y,
                  uint16_t color, const GFXfont* font) {
    g_tft.setFont(font);
    g_tft.setTextColor(color);
    int16_t  x1, y1;
    uint16_t w, h;
    g_tft.getTextBounds(s, 0, 0, &x1, &y1, &w, &h);
    int16_t cx = (kScreenWidth - static_cast<int16_t>(w)) / 2;
    if (cx < 0) cx = 0;
    g_tft.setCursor(cx, baseline_y);
    g_tft.print(s);
}

// Compose the clock + date strings for the current moment from the host-
// supplied unix_ts + utc_offset, advancing via millis() since capture.
void composeIdleStrings(const QuotaSnapshot& q, uint64_t now_ms,
                        char* clock_out, size_t clock_sz,
                        char* date_out,  size_t date_sz) {
    if (q.unix_ts == 0) {
        std::strncpy(clock_out, "--:--", clock_sz);
        clock_out[clock_sz - 1] = '\0';
        std::strncpy(date_out, "set time via BLE", date_sz);
        date_out[date_sz - 1] = '\0';
        return;
    }

    uint32_t elapsed_s = 0;
    if (q.time_capture_ms > 0 && now_ms >= q.time_capture_ms) {
        elapsed_s = static_cast<uint32_t>(
            (now_ms - q.time_capture_ms) / 1000ULL);
    }
    time_t now_unix_utc   = static_cast<time_t>(q.unix_ts) + elapsed_s;
    time_t now_unix_local = now_unix_utc +
                            static_cast<time_t>(q.utc_offset_min) * 60;

    struct tm tm_buf;
    gmtime_r(&now_unix_local, &tm_buf);

    std::snprintf(clock_out, clock_sz, "%02d:%02d",
                  tm_buf.tm_hour, tm_buf.tm_min);

    static const char* kWday[] = {
        "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
    static const char* kMon[] = {
        "Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
    int wday = tm_buf.tm_wday & 7;
    int mon  = tm_buf.tm_mon  % 12;
    if (mon < 0) mon = 0;
    std::snprintf(date_out, date_sz, "%s %s %d %d",
                  kWday[wday], kMon[mon], tm_buf.tm_mday,
                  1900 + tm_buf.tm_year);
}

// ASCII-art kitty in Claude orange. 7-character text rendered at
// textSize=2 (12×16 px per cell). Each mood has its own normal +
// blink frame so the cat actually expresses what Claude Code is doing
// to your quota.
struct PetSprite {
    const char* normal;
    const char* blink;
};
constexpr PetSprite kPetSprites[kPetMoodCount] = {
    /* HAPPY       */ {"(=^.^=)", "(=^_^=)"},
    /* CALM        */ {"(='.'=)", "(=-.-=)"},
    /* TIRED       */ {"(=u.u=)", "(=u_u=)"},
    /* STRESSED    */ {"(=>.<=)", "(=>_<=)"},
    /* OVERWHELMED */ {"(=T.T=)", "(=T_T=)"},
};

void drawPetFrameAt(int16_t cx, int16_t cy,
                    int8_t /*walk_frame*/, int8_t eye_frame,
                    int8_t mood) {
    if (mood < 0 || mood >= kPetMoodCount) mood = kPetMoodHappy;
    const PetSprite& sprites = kPetSprites[mood];
    const char* text = (eye_frame == 1) ? sprites.blink : sprites.normal;

    g_tft.setFont();                 // null → default 6×8 bitmap font
    g_tft.setTextSize(2);
    g_tft.setTextColor(kColorClaude);

    int16_t  x1, y1;
    uint16_t w, h;
    g_tft.getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
    g_tft.setCursor(cx - static_cast<int16_t>(w) / 2,
                    cy - static_cast<int16_t>(h) / 2);
    g_tft.print(text);

    g_tft.setTextSize(1);            // restore
}

// Erase the sprite area at a given (cx, cy). Used when the cat moves so
// the trail behind it doesn't smear.
void erasePetAt(int16_t cx, int16_t cy) {
    if (cx < 0) return;
    g_tft.fillRect(cx - kIdlePetHalfW - 1,
                   kIdlePetTopY,
                   kIdlePetHalfW * 2 + 2,
                   kIdlePetBotY - kIdlePetTopY + 1,
                   kColorBg);
    (void)cy;
}

void drawIdleBody(const QuotaSnapshot& q, uint64_t now_ms,
                  bool force_full) {
    char clock_buf[8];
    char date_buf[24];
    composeIdleStrings(q, now_ms,
                       clock_buf, sizeof(clock_buf),
                       date_buf,  sizeof(date_buf));

    const bool full = force_full || !g_last_idle.initialized;
    if (full) {
        g_tft.fillScreen(kColorBg);
        // Reset cached pet position so the next displayTickPet repaints
        // immediately at the correct walk-phase coordinates.
        g_pet_last_x          = -1;
        g_pet_last_y          = -1;
        g_pet_frame_drawn     = -1;
        g_pet_last_walk_frame = -1;
        g_pet_last_mood       = -1;
        // Separator line under the date.
        g_tft.drawFastHLine(kRowMargin * 2, kIdleSeparatorY,
                            kScreenWidth - 4 * kRowMargin, kColorMuted);
    }

    if (full || std::strncmp(clock_buf, g_last_idle.clock_text,
                             sizeof(g_last_idle.clock_text)) != 0) {
        g_tft.fillRect(0, kIdleClockRowY, kScreenWidth, kIdleClockRowH,
                       kColorBg);
        drawCentered(clock_buf, kIdleClockBaselineY,
                     kColorFg, &FreeSansBold24pt7b);
        std::strncpy(g_last_idle.clock_text, clock_buf,
                     sizeof(g_last_idle.clock_text) - 1);
        g_last_idle.clock_text[sizeof(g_last_idle.clock_text) - 1] = '\0';
    }

    if (full || std::strncmp(date_buf, g_last_idle.date_text,
                             sizeof(g_last_idle.date_text)) != 0) {
        g_tft.fillRect(0, kIdleDateRowY, kScreenWidth, kIdleDateRowH,
                       kColorBg);
        drawCentered(date_buf, kIdleDateBaselineY,
                     kColorMuted, &FreeSans12pt7b);
        std::strncpy(g_last_idle.date_text, date_buf,
                     sizeof(g_last_idle.date_text) - 1);
        g_last_idle.date_text[sizeof(g_last_idle.date_text) - 1] = '\0';
    }

    if (full || std::strncmp(q.idle_status, g_last_idle.status_text,
                             sizeof(g_last_idle.status_text)) != 0) {
        g_tft.fillRect(0, kIdleStatusRowY, kScreenWidth, kIdleStatusRowH,
                       kColorBg);
        if (q.idle_status[0] != '\0') {
            drawCentered(q.idle_status, kIdleStatusBaselineY,
                         kColorGreen, &FreeSans12pt7b);
        }
        std::strncpy(g_last_idle.status_text, q.idle_status,
                     sizeof(g_last_idle.status_text) - 1);
        g_last_idle.status_text[sizeof(g_last_idle.status_text) - 1] = '\0';
    }

    g_last_idle.initialized = true;
}

void drawApiBody(uint32_t cost_micro_usd, uint32_t duration_s) {
    // Wipe the entire 5h+7d body region.
    g_tft.fillRect(0, k5hRowY,
                   kScreenWidth, (k7dRowY + k7dRowH) - k5hRowY,
                   kColorBg);

    // Cost: format as $X.XX (two decimals). 1_000_000 micro-USD = $1.00.
    char cost_buf[16];
    const unsigned dollars  = cost_micro_usd / 1000000u;
    const unsigned cents100 = (cost_micro_usd % 1000000u) / 10000u;  // 0..99
    std::snprintf(cost_buf, sizeof(cost_buf), "$%u.%02u", dollars, cents100);
    // Center horizontally, baseline a bit below the row midpoint.
    g_tft.setFont(&FreeSansBold24pt7b);
    int16_t  x1, y1;
    uint16_t w, h;
    g_tft.getTextBounds(cost_buf, 0, 0, &x1, &y1, &w, &h);
    const int16_t cx = (kScreenWidth - static_cast<int16_t>(w)) / 2;
    const int16_t cy = k5hRowY + 60;
    printAt(cost_buf, cx, cy, kColorGreen, &FreeSansBold24pt7b);

    // Duration label.
    char dur_buf[24];
    if (duration_s == 0) {
        std::strncpy(dur_buf, "", sizeof(dur_buf));
    } else {
        char tmp[16];
        formatDuration(duration_s, tmp, sizeof(tmp));
        std::snprintf(dur_buf, sizeof(dur_buf), "t: %s", tmp);
    }
    if (dur_buf[0] != '\0') {
        g_tft.setFont(&FreeSans9pt7b);
        g_tft.getTextBounds(dur_buf, 0, 0, &x1, &y1, &w, &h);
        const int16_t dx = (kScreenWidth - static_cast<int16_t>(w)) / 2;
        printAt(dur_buf, dx, k7dRowY + 50, kColorMuted, &FreeSans9pt7b);
    }
}

// ---------------------------------------------------------------- footer --
void drawFooter(const QuotaSnapshot& quota, uint64_t now_ms) {
    // Logo region: 40×40, paired with the 40×40 GIF on the far right.
    // Logo at X=156..195, GIF at X=200..240, 4-px gap between them.
    // Both centred on kStarCy=223 so they look balanced. The logo
    // overflows the footer top/bot by a few px into the surrounding
    // gap regions — that area is blank in the normal HUD layout.
    constexpr int16_t kFooterTextRightCap = 152;
    constexpr int16_t kFooterLogoX        = 156;
    constexpr int16_t kFooterLogoY        = kStarCy - kLogoH / 2;

    g_tft.fillRect(0, kFooterY, kFooterTextRightCap, kFooterH, kColorBg);
    // Wipe the logo's bbox before re-drawing so an OLD bigger logo can't
    // leave residue if we ever shrink it.
    g_tft.fillRect(kFooterLogoX, kFooterLogoY, kLogoW, kLogoH, kColorBg);
    g_tft.drawRGBBitmap(kFooterLogoX, kFooterLogoY,
                         const_cast<uint16_t*>(kLogo), kLogoW, kLogoH);

    char buf[40];
    uint16_t color;

    if (quota.last_update_ms == kTsUnset) {
        std::strncpy(buf, "waiting for data...", sizeof(buf));
        buf[sizeof(buf) - 1] = '\0';
        color = kColorMuted;
        g_last.footer_stale_min = -1;
        g_last.footer_stale_red = false;
    } else {
        const uint64_t delta_ms = (now_ms >= quota.last_update_ms)
                                      ? (now_ms - quota.last_update_ms)
                                      : 0;
        const uint32_t delta_min =
            static_cast<uint32_t>(delta_ms / 60000ULL);
        const bool stale = delta_min >= kStaleThresholdMin;
        if (stale) {
            std::snprintf(buf, sizeof(buf), "stale %lum",
                          static_cast<unsigned long>(delta_min));
            color = kColorRed;
        } else {
            std::snprintf(buf, sizeof(buf), "updated %lum ago",
                          static_cast<unsigned long>(delta_min));
            color = kColorMuted;
        }
        g_last.footer_stale_min = static_cast<int32_t>(delta_min);
        g_last.footer_stale_red = stale;
    }

    printAt(buf, kRowMargin, kFooterY + 18, color, &FreeSans9pt7b);
}

}  // namespace

// =========================================================== public API ===
void displayInit() {
    pinMode(kPinLcdBl, OUTPUT);
    digitalWrite(kPinLcdBl, HIGH);

    // SCK, MISO (unused), MOSI, CS — explicit to leave nothing to library default.
    g_spi.begin(kPinLcdSclk, /*MISO=*/-1, kPinLcdMosi, kPinLcdCs);

    g_tft.init(kScreenWidth, kScreenHeight, SPI_MODE0);
    g_tft.setSPISpeed(40 * 1000 * 1000);  // 40 MHz — 4× former conservative
    g_tft.setRotation(0);
    g_tft.fillScreen(kColorBg);

    g_last = LastDrawnState{};
}

void displayRender(const DisplayView& view, bool full_redraw) {
    const QuotaSnapshot& q = view.quota;
    const uint8_t mode = q.mode;

    // ---- idle mode: takes over the whole screen ----
    if (mode == kSnapshotModeIdle) {
        // Mode flip from non-idle → idle: wipe everything once, then let
        // drawIdleBody's per-region diff cache take over.
        const bool flip_into_idle =
            (g_last.body_mode_drawn != -1) &&
            (g_last.body_mode_drawn != static_cast<int8_t>(mode));
        drawIdleBody(q, view.now_ms, full_redraw || flip_into_idle);
        if (flip_into_idle) {
            // Force HUD caches to be invalidated when we come back later.
            g_last = LastDrawnState{};
        }
        g_last.body_mode_drawn = static_cast<int8_t>(mode);
        return;
    }

    // Leaving idle mode (coming back into hud)? Reset idle cache and wipe.
    if (g_last.body_mode_drawn == static_cast<int8_t>(kSnapshotModeIdle)) {
        g_last_idle = LastDrawnIdle{};
        g_pet_last_x          = -1;
        g_pet_last_y          = -1;
        g_pet_frame_drawn     = -1;
        g_pet_last_walk_frame = -1;
        g_pet_last_mood       = -1;
        g_tft.fillScreen(kColorBg);
        g_last = LastDrawnState{};
        full_redraw = true;
    }

    // ---- header ----
    const bool title_changed = std::strncmp(g_last.title, q.title,
                                            sizeof(g_last.title)) != 0;
    if (full_redraw ||
        !g_last.header_drawn ||
        title_changed ||
        g_last.ble_connected != view.ble_connected) {
        drawHeader(q.title, view.ble_connected);
        g_last.header_drawn  = true;
        g_last.ble_connected = view.ble_connected;
        std::strncpy(g_last.title, q.title, sizeof(g_last.title) - 1);
        g_last.title[sizeof(g_last.title) - 1] = '\0';
    }

    // If we're switching modes, wipe both rows and reset their caches.
    const bool mode_flip = (g_last.body_mode_drawn != -1) &&
                           (g_last.body_mode_drawn != static_cast<int8_t>(mode));
    const bool body_full = full_redraw || mode_flip || g_last.body_mode_drawn == -1;
    if (mode_flip) {
        g_tft.fillRect(0, k5hRowY,
                       kScreenWidth, (k7dRowY + k7dRowH) - k5hRowY, kColorBg);
        g_last.pct_5h = -1; g_last.pct_7d = -1;
        g_last.used_5h = 0xFFFF; g_last.limit_5h = 0xFFFF;
        g_last.used_7d = 0xFFFF; g_last.limit_7d = 0xFFFF;
        g_last.reset_label_5h[0] = '\0';
        g_last.reset_label_7d[0] = '\0';
        g_last.cost_micro_usd = 0xFFFFFFFFu;
        g_last.duration_s     = 0xFFFFFFFFu;
    }

    if (mode == kSnapshotModeApi) {
        // ---- API body: cost + duration ----
        if (body_full ||
            g_last.cost_micro_usd != q.cost_micro_usd ||
            g_last.duration_s     != q.duration_s) {
            drawApiBody(q.cost_micro_usd, q.duration_s);
            g_last.cost_micro_usd = q.cost_micro_usd;
            g_last.duration_s     = q.duration_s;
        }
    } else {
        // ---- Subscription body: 5H + 7D rows with reset countdowns ----
        char reset_5h[16];
        char reset_7d[16];
        formatRemaining(
            liveRemainingS(q.reset_in_s_5h, q.last_update_ms, view.now_ms),
            reset_5h, sizeof(reset_5h));
        formatRemaining(
            liveRemainingS(q.reset_in_s_7d, q.last_update_ms, view.now_ms),
            reset_7d, sizeof(reset_7d));

        const uint8_t pct_5h = computePercent(q.used_5h, q.limit_5h);
        if (body_full ||
            g_last.pct_5h   != pct_5h ||
            g_last.used_5h  != q.used_5h ||
            g_last.limit_5h != q.limit_5h ||
            std::strncmp(g_last.reset_label_5h, reset_5h,
                         sizeof(g_last.reset_label_5h)) != 0) {
            drawRow("5H", reset_5h, k5hRowY, q.used_5h, q.limit_5h, pct_5h);
            g_last.pct_5h   = pct_5h;
            g_last.used_5h  = q.used_5h;
            g_last.limit_5h = q.limit_5h;
            std::strncpy(g_last.reset_label_5h, reset_5h,
                         sizeof(g_last.reset_label_5h) - 1);
            g_last.reset_label_5h[sizeof(g_last.reset_label_5h) - 1] = '\0';
        }

        const uint8_t pct_7d = computePercent(q.used_7d, q.limit_7d);
        if (body_full ||
            g_last.pct_7d   != pct_7d ||
            g_last.used_7d  != q.used_7d ||
            g_last.limit_7d != q.limit_7d ||
            std::strncmp(g_last.reset_label_7d, reset_7d,
                         sizeof(g_last.reset_label_7d)) != 0) {
            drawRow("7D", reset_7d, k7dRowY, q.used_7d, q.limit_7d, pct_7d);
            g_last.pct_7d   = pct_7d;
            g_last.used_7d  = q.used_7d;
            g_last.limit_7d = q.limit_7d;
            std::strncpy(g_last.reset_label_7d, reset_7d,
                         sizeof(g_last.reset_label_7d) - 1);
            g_last.reset_label_7d[sizeof(g_last.reset_label_7d) - 1] = '\0';
        }
    }

    g_last.body_mode_drawn = static_cast<int8_t>(mode);

    // ---- footer ----
    drawFooter(q, view.now_ms);
}

// Pet animation tick. Picks position + blink frame for the current
// millis() and repaints only when something changed. The cat walks
// across the top of the screen in a triangle-wave pattern, bobs Y
// every half-second to suggest stepping, and blinks every 4 seconds.
// Random-walk state: at random intervals we pick a new target X and
// smoothly lerp toward it. Gives the cat a wandering, less-mechanical
// feel than a triangle wave.
int16_t  g_pet_target_x       = (kIdlePetMinX + kIdlePetMaxX) / 2;
uint32_t g_pet_next_retarget  = 0;

// Per-mood movement profile. retarget interval shapes how often the
// cat picks a new destination, smoothing_divisor controls the glide
// speed (lower = faster glide). OVERWHELMED holds position.
struct PetMovementProfile {
    uint32_t retarget_min_ms;
    uint32_t retarget_max_ms;
    int16_t  smoothing_divisor;  // higher = slower glide
    bool     stops_in_centre;
};
constexpr PetMovementProfile kPetMovement[kPetMoodCount] = {
    /* HAPPY       */ {3500, 6500,  12, false},
    /* CALM        */ {3000, 6000,  14, false},
    /* TIRED       */ {4500, 8500,  20, false},
    /* STRESSED    */ {1200, 2500,   6, false},
    /* OVERWHELMED */ {99999, 99999, 1,  true },
};

// Claude splatter-star "thinking" loader (matches Claude iOS icon).
// Each ray has a fixed irregular base length + an independent slow
// shimmer (±12% length wobble, phase-offset per ray so they don't
// move in unison). The whole star rotates very slowly. Subtle — no
// dramatic pulsing, no "blinking" feel.
// Animated star: pick a pre-rendered RGB565 frame from kStarFrames[]
// based on now_ms and push it with one DMA SPI burst. Zero CPU spent
// on math each tick — the heavy lifting was done at build time.
constexpr uint32_t kStarFrameMs = 100;  // 100 ms × 8 frames = 0.8s/loop, fluid

void drawClaudeStar(uint64_t now_ms) {
    const int frame = static_cast<int>((now_ms / kStarFrameMs) % kStarFrameCount);
    g_tft.drawRGBBitmap(
        kStarCx - kStarFrameW / 2,
        kStarCy - kStarFrameH / 2,
        const_cast<uint16_t*>(kStarFrames[frame]),
        kStarFrameW, kStarFrameH);
}

void eraseClaudeStar() {
    g_tft.fillRect(kStarCx - kStarFrameW / 2,
                   kStarCy - kStarFrameH / 2,
                   kStarFrameW, kStarFrameH, kColorBg);
}

// Idle indicator — three horizontal dots, dim orange. Reads as "ready
// but at rest", like typing-dots that aren't actively typing. Replaces
// the spiky dim-splatter look that felt hostile.
void drawIdleDots() {
    constexpr int kDotR     = 3;
    constexpr int kDotGap   = 11;   // centre-to-centre spacing
    constexpr int kDotCount = 3;

    g_tft.fillRect(kStarCx - kIconW / 2, kStarCy - kIconH / 2,
                   kIconW, kIconH, kColorBg);

    const int total_w = (kDotCount - 1) * kDotGap;
    const int x0 = kStarCx - total_w / 2;
    for (int i = 0; i < kDotCount; ++i) {
        g_tft.fillCircle(x0 + i * kDotGap, kStarCy, kDotR, kColorClaudeDim);
    }
}

// Cache so we erase exactly once when thinking goes false.
bool g_star_was_drawn = false;

void displayTickPet(uint64_t now_ms, PetMood mood) {
    int8_t m = (mood < 0 || mood >= kPetMoodCount) ? kPetMoodHappy
                                                    : static_cast<int8_t>(mood);
    const PetMovementProfile& mv = kPetMovement[m];

    // Mood flipped → force a redraw and pick a fresh target.
    bool force_redraw = false;
    if (m != g_pet_last_mood) {
        g_pet_last_mood = m;
        g_pet_next_retarget = 0;  // retarget now
        force_redraw = true;
    }

    // OVERWHELMED stops in the centre (cat is too sad to walk).
    if (mv.stops_in_centre) {
        g_pet_target_x = (kIdlePetMinX + kIdlePetMaxX) / 2;
    } else if (static_cast<uint32_t>(now_ms) >= g_pet_next_retarget) {
        g_pet_target_x = static_cast<int16_t>(
            random(kIdlePetMinX, kIdlePetMaxX + 1));
        g_pet_next_retarget = static_cast<uint32_t>(now_ms) +
            static_cast<uint32_t>(random(mv.retarget_min_ms,
                                          mv.retarget_max_ms + 1));
    }

    // Smooth glide toward target.
    int16_t cx;
    if (g_pet_last_x < 0) {
        cx = g_pet_target_x;
    } else {
        const int32_t delta = g_pet_target_x - g_pet_last_x;
        cx = static_cast<int16_t>(
            g_pet_last_x + delta / mv.smoothing_divisor);
        if (cx == g_pet_last_x && delta != 0) {
            cx += (delta > 0) ? 1 : -1;
        }
    }
    if (cx < kIdlePetMinX) cx = kIdlePetMinX;
    if (cx > kIdlePetMaxX) cx = kIdlePetMaxX;

    // Bob Y — OVERWHELMED doesn't bob (sits sadly).
    const int16_t cy = (mv.stops_in_centre)
        ? kIdlePetBaseY
        : ((static_cast<uint32_t>(now_ms / kIdlePetBobPeriodMs) & 1)
            ? (kIdlePetBaseY + kIdlePetBobAmpY)
            : kIdlePetBaseY);

    // Blink.
    const uint32_t blink_phase =
        static_cast<uint32_t>(now_ms % kIdlePetBlinkPeriodMs);
    const int8_t eye_frame = (blink_phase >= (kIdlePetBlinkPeriodMs -
                                              kIdlePetBlinkDurMs)) ? 1 : 0;

    const bool same_y   = (cy == g_pet_last_y);
    const bool same_eye = (eye_frame == g_pet_frame_drawn);
    const int  dx       = (g_pet_last_x < 0) ? 9999 : (cx - g_pet_last_x);
    const int  abs_dx   = dx < 0 ? -dx : dx;
    if (!force_redraw && abs_dx < 2 && same_y && same_eye) {
        return;
    }

    erasePetAt(g_pet_last_x, g_pet_last_y);
    drawPetFrameAt(cx, cy, /*walk_frame=*/0, eye_frame, m);
    g_pet_last_x          = cx;
    g_pet_last_y          = cy;
    g_pet_frame_drawn     = eye_frame;
    g_pet_last_walk_frame = 0;
}

void displayTickStar(uint64_t now_ms, bool thinking) {
    if (thinking) {
        drawClaudeStar(now_ms);
        g_star_was_drawn = true;
    } else if (g_star_was_drawn) {
        eraseClaudeStar();
        g_star_was_drawn = false;
    }
}

// ─── App-state display (replaces the old thinking-only star) ──────────────
//
// Same 40×40 slot as the Claude splatter star. State machine:
//   idle      → erase, leave blank
//   thinking  → splatter star animation (reuses drawClaudeStar)
//   tool      → tool icon mapped from `detail` (longest-prefix match)
//   waiting   → pulsing orange dot
//
// Cached so unchanged ticks are cheap.
int8_t g_last_state_drawn    = kAppStateUnset;
char   g_last_state_detail[kAppStateDetailMaxLen + 1] = {0};
int8_t g_last_icon_idx       = -1;

// Find the longest-matching prefix in kIconMap for the given tool name.
// Returns -1 if no entry matches.
int8_t lookupIconForTool(const char* tool_name) {
    if (!tool_name || !*tool_name) return -1;
    int8_t best_idx  = -1;
    size_t best_len  = 0;
    for (int i = 0; i < kIconMapLen; ++i) {
        const char* p = kIconMap[i].prefix;
        const size_t plen = std::strlen(p);
        if (std::strncmp(tool_name, p, plen) == 0 && plen > best_len) {
            best_idx = kIconMap[i].icon_idx;
            best_len = plen;
        }
    }
    return best_idx;
}

void drawToolIcon(int8_t icon_idx) {
    if (icon_idx < 0 || icon_idx >= kIconCount) return;
    // Erase the slot first so previous content (idle/waiting/star) is gone.
    g_tft.fillRect(kStarCx - kIconW / 2, kStarCy - kIconH / 2,
                   kIconW, kIconH, kColorBg);
    g_tft.drawRGBBitmap(
        kStarCx - kIconW / 2,
        kStarCy - kIconH / 2,
        const_cast<uint16_t*>(kIcons[icon_idx]),
        kIconW, kIconH);
}

void drawWaitingPulse(uint64_t now_ms) {
    // Pulsing orange dot. 1.2 s period, radius 4..12 px.
    constexpr uint32_t kWaitPeriod = 1200;
    const float t = static_cast<float>(now_ms % kWaitPeriod) /
                    static_cast<float>(kWaitPeriod);
    const float pulse = (sinf(t * 6.28318530718f) + 1.0f) * 0.5f;
    const int r = 4 + static_cast<int>(pulse * 8);

    // Wipe the FULL 40×40 sprite slot — anything less leaves a halo of
    // the previous icon (Bash/MCP/etc.) visible around the dot.
    g_tft.fillRect(kStarCx - kIconW / 2, kStarCy - kIconH / 2,
                   kIconW, kIconH, kColorBg);
    g_tft.fillCircle(kStarCx, kStarCy, r, kColorClaude);
}

void displayTickState(uint64_t now_ms, AppState state, const char* detail) {
    if (state == kAppStateUnset) return;

    // Detect state transition or detail change.
    const bool state_changed = (state != g_last_state_drawn);
    const bool detail_changed =
        (state == kAppStateTool) &&
        (std::strncmp(detail, g_last_state_detail, kAppStateDetailMaxLen) != 0);

    switch (state) {
        case kAppStateIdle: {
            if (state_changed) {
                // Three dim dots — "ready, resting".
                drawIdleDots();
            }
            break;
        }
        case kAppStateThinking: {
            // Reuse the splatter star animation.
            drawClaudeStar(now_ms);
            g_star_was_drawn = true;
            break;
        }
        case kAppStateTool: {
            if (state_changed || detail_changed) {
                const int8_t idx = lookupIconForTool(detail);
                // Fall back to MCP icon (last entry) if no match.
                const int8_t draw_idx = (idx >= 0) ? idx : (kIconCount - 1);
                drawToolIcon(draw_idx);
                g_last_icon_idx = draw_idx;
                std::strncpy(g_last_state_detail, detail,
                             sizeof(g_last_state_detail) - 1);
                g_last_state_detail[sizeof(g_last_state_detail) - 1] = '\0';
            }
            break;
        }
        case kAppStateWaiting: {
            drawWaitingPulse(now_ms);
            break;
        }
        default: break;
    }

    g_last_state_drawn = state;
}

void displayTickFooter(const QuotaSnapshot& quota, uint64_t now_ms) {
    // Skip if the minute counter has not changed.
    if (quota.last_update_ms == kTsUnset) {
        if (g_last.footer_stale_min == -1) {
            return;
        }
    } else {
        const uint64_t delta_ms = (now_ms >= quota.last_update_ms)
                                      ? (now_ms - quota.last_update_ms)
                                      : 0;
        const uint32_t delta_min = static_cast<uint32_t>(delta_ms / 60000ULL);
        const bool     stale     = delta_min >= kStaleThresholdMin;
        if (static_cast<int32_t>(delta_min) == g_last.footer_stale_min &&
            stale == g_last.footer_stale_red) {
            return;
        }
    }
    drawFooter(quota, now_ms);
}

void displayUpdateConnection(bool connected) {
    if (g_last.header_drawn && g_last.ble_connected == connected) {
        return;
    }
    drawHeaderDot(connected);
    g_last.ble_connected = connected;
    g_last.header_drawn  = true;
}

void displayFlashAlert() {
    for (uint8_t i = 0; i < kAlertFlashCycles; ++i) {
        g_tft.fillScreen(kColorRed);
        delay(kAlertFlashIntervalMs);
        g_tft.fillScreen(kColorBg);
        delay(kAlertFlashIntervalMs);
    }
    // Invalidate the cache so the next displayRender repaints everything.
    g_last = LastDrawnState{};
}

// ============================================================ OTA mode ===
//
// While an OTA is in progress (the BLE OTA task is streaming firmware into
// the inactive flash slot) we take over the screen with a big progress
// readout. displayRender / displayTickFooter become no-ops via the
// `g_ota_active` flag so the HUD doesn't overpaint us.
//
// Layout (centered):
//   y=30   "OTA UPDATE" (bold 12pt)
//   y=110  "<PCT>%"     (bold 24pt, green)
//   y=160  progress bar (kBarHeight*2 tall)
//   y=210  "<received> / <total> B" (9pt muted)

namespace {
volatile bool g_ota_active   = false;
int16_t       g_ota_last_pct = -1;

void drawOtaFrame(uint32_t received, uint32_t total, int16_t pct) {
    char buf[40];

    // Header bar.
    g_tft.fillRect(0, 0, kScreenWidth, 50, kColorBg);
    printAt("OTA UPDATE",
            kRowMargin, 30, kColorFg, &FreeSansBold12pt7b);

    // Big percentage, centered.
    std::snprintf(buf, sizeof(buf), "%d%%", static_cast<int>(pct));
    g_tft.setFont(&FreeSansBold24pt7b);
    int16_t  x1, y1;
    uint16_t w, h;
    g_tft.getTextBounds(buf, 0, 0, &x1, &y1, &w, &h);
    g_tft.fillRect(0, 80, kScreenWidth, 50, kColorBg);
    g_tft.setCursor((kScreenWidth - static_cast<int16_t>(w)) / 2, 120);
    g_tft.setTextColor(kColorGreen);
    g_tft.print(buf);

    // Progress bar.
    const int16_t bar_x = 20;
    const int16_t bar_y = 160;
    const int16_t bar_w = kScreenWidth - 40;
    const int16_t bar_h = kBarHeight * 2;
    g_tft.fillRect(bar_x, bar_y, bar_w, bar_h, kColorBarTrack);
    const int16_t fill_w =
        static_cast<int16_t>((static_cast<int32_t>(bar_w) * pct) / 100);
    if (fill_w > 0) {
        g_tft.fillRect(bar_x, bar_y, fill_w, bar_h, kColorGreen);
    }
    g_tft.drawRect(bar_x, bar_y, bar_w, bar_h, kColorMuted);

    // Bytes counter.
    std::snprintf(buf, sizeof(buf), "%u / %u B",
                  static_cast<unsigned>(received),
                  static_cast<unsigned>(total));
    g_tft.fillRect(0, 200, kScreenWidth, 30, kColorBg);
    g_tft.setFont(&FreeSans9pt7b);
    g_tft.getTextBounds(buf, 0, 0, &x1, &y1, &w, &h);
    g_tft.setCursor((kScreenWidth - static_cast<int16_t>(w)) / 2, 220);
    g_tft.setTextColor(kColorMuted);
    g_tft.print(buf);
}
}  // anon namespace

void displayBeginOta() {
    g_ota_active   = true;
    g_ota_last_pct = -1;
    g_tft.fillScreen(kColorBg);
    drawOtaFrame(0, 1, 0);
}

void displayOtaProgress(uint32_t received, uint32_t total) {
    if (!g_ota_active) {
        // First call without an explicit begin — set up the screen first.
        displayBeginOta();
    }
    if (total == 0) return;
    int16_t pct = static_cast<int16_t>(
        (static_cast<uint64_t>(received) * 100ULL) / total);
    if (pct > 100) pct = 100;
    if (pct == g_ota_last_pct) {
        return;  // cheap path: nothing to redraw at this granularity
    }
    g_ota_last_pct = pct;
    drawOtaFrame(received, total, pct);
}

bool displayIsOtaActive() {
    return g_ota_active;
}

Adafruit_ST7789& displayGetTft() {
    return g_tft;
}

}  // namespace cc_hud
