#!/usr/bin/env python3
"""
Generate the Claude "thinking" splatter-star frame sequence and emit
it as a C header for the firmware.

40x40 px RGB565 frames, N frames cycling through one full rotation +
per-frame ray-length shimmer. Output:
    firmware/src/claude_star_frames.h
"""

from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageDraw

# ---- tunables ------------------------------------------------------------
FRAME_W       = 40
FRAME_H       = 40
FRAME_COUNT   = 12              # 12 frames → 12.5 FPS at 80 ms tick
CENTRE        = (FRAME_W // 2, FRAME_H // 2)
RAY_COUNT     = 12
BASE_HALF_W   = 2.6             # ray base half-width in px
CORE_R        = 3
ORANGE        = (215, 119, 87)  # #D77757
BG            = (0, 0, 0)

# Per-ray base length (irregular splatter shape).
BASE_LENGTHS = [16, 13, 15, 11, 17, 12, 14, 11, 16, 13, 15, 11]

# Shimmer amplitude (each ray length wobbles independently).
SHIMMER_AMP = 0.10

# Total rotation across the whole loop (radians).
TOTAL_ROT_RAD = 2 * math.pi      # one full revolution per loop


# ---- render one frame ----------------------------------------------------
def render_frame(frame_idx: int) -> Image.Image:
    img = Image.new('RGB', (FRAME_W, FRAME_H), BG)
    draw = ImageDraw.Draw(img)
    cx, cy = CENTRE

    rot = (frame_idx / FRAME_COUNT) * TOTAL_ROT_RAD
    shimmer_phase = (frame_idx / FRAME_COUNT) * 2 * math.pi

    for i in range(RAY_COUNT):
        ang = rot + (i / RAY_COUNT) * 2 * math.pi
        ray_phase = shimmer_phase + (i / RAY_COUNT) * 2 * math.pi
        wobble = 1.0 + SHIMMER_AMP * math.sin(ray_phase)
        L = BASE_LENGTHS[i] * wobble

        if L < 2:
            continue

        ac, asn = math.cos(ang), math.sin(ang)
        pc, ps  = -asn, ac            # perpendicular

        p1 = (cx + pc * BASE_HALF_W, cy + ps * BASE_HALF_W)
        p2 = (cx - pc * BASE_HALF_W, cy - ps * BASE_HALF_W)
        p3 = (cx + ac * L,           cy + asn * L)
        draw.polygon([p1, p2, p3], fill=ORANGE)

    draw.ellipse((cx - CORE_R, cy - CORE_R,
                  cx + CORE_R, cy + CORE_R), fill=ORANGE)
    return img


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def write_header(frames: list[Image.Image], out_path: Path) -> None:
    with out_path.open('w', encoding='ascii') as f:
        f.write('// Auto-generated by tools/generate_star_frames.py.\n')
        f.write('// Claude "thinking" splatter-star, RGB565 frames.\n')
        f.write('#pragma once\n\n')
        f.write('#include <cstdint>\n\n')
        f.write(f'constexpr int kStarFrameW     = {FRAME_W};\n')
        f.write(f'constexpr int kStarFrameH     = {FRAME_H};\n')
        f.write(f'constexpr int kStarFrameCount = {len(frames)};\n\n')
        f.write('constexpr uint16_t kStarFrames'
                '[kStarFrameCount][kStarFrameW * kStarFrameH] = {\n')
        for fi, img in enumerate(frames):
            f.write(f'    // frame {fi}\n    {{\n')
            for y in range(FRAME_H):
                row = []
                for x in range(FRAME_W):
                    r, g, b = img.getpixel((x, y))[:3]
                    row.append(f'0x{rgb_to_565(r, g, b):04X}')
                f.write('        ' + ','.join(row) + ',\n')
            f.write('    },\n')
        f.write('};\n')


def main() -> None:
    frames = [render_frame(i) for i in range(FRAME_COUNT)]

    out_dir = Path(__file__).resolve().parents[1] / 'src'
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / 'claude_star_frames.h'
    write_header(frames, out_path)

    bytes_per_frame = FRAME_W * FRAME_H * 2
    total_bytes     = bytes_per_frame * FRAME_COUNT
    print(f'wrote {out_path}')
    print(f'  {FRAME_COUNT} frames × {FRAME_W}×{FRAME_H} RGB565 '
          f'= {total_bytes // 1024} KB in flash')

    # Optional preview: dump frame 0 as PNG so you can sanity-check.
    preview = Path(__file__).parent / 'star_preview.png'
    frames[0].save(preview)
    print(f'  preview: {preview}')


if __name__ == '__main__':
    main()
