#!/usr/bin/env python3
"""
gif_to_buffer.py — convert any animated GIF into the RGB565 C header
format the firmware expects (drop-in replacement for the file generated
by generate_star_frames.py).

Usage:
    gif_to_buffer.py PATH/TO/animation.gif [--size 40] [--frames 12]

Output:
    firmware/src/claude_star_frames.h

Notes:
    --size N        target W = H, default 40. The firmware draws the
                    frame at (kStarCx - W/2, kStarCy - H/2); pick a
                    size that fits the spot (≤44 px wide, ≤40 tall
                    given the current footer layout).
    --frames N      cap on frame count (down-samples if the GIF has
                    more). Each extra frame ≈ size² × 2 bytes of flash.
    --bg "0,0,0"    transparent-pixel fallback colour (default black).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageSequence


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def resize_with_alpha(frame: Image.Image, size: int,
                       bg: tuple[int, int, int]) -> Image.Image:
    """Composite onto an opaque background, then resize to (size, size)."""
    if frame.mode != 'RGBA':
        frame = frame.convert('RGBA')
    canvas = Image.new('RGBA', frame.size, bg + (255,))
    canvas.alpha_composite(frame)
    canvas = canvas.convert('RGB')
    # Fit the GIF into a square: scale longest side to `size`, centre on bg.
    w, h = canvas.size
    scale = size / max(w, h)
    new_w, new_h = max(1, int(round(w * scale))), max(1, int(round(h * scale)))
    canvas = canvas.resize((new_w, new_h), Image.LANCZOS)
    square = Image.new('RGB', (size, size), bg)
    square.paste(canvas, ((size - new_w) // 2, (size - new_h) // 2))
    return square


def load_frames(gif_path: Path, size: int, max_frames: int,
                bg: tuple[int, int, int]) -> list[Image.Image]:
    img = Image.open(gif_path)
    raw = [f.copy() for f in ImageSequence.Iterator(img)]
    if len(raw) == 0:
        raise RuntimeError('GIF has no frames')

    # Down-sample evenly if too many frames.
    if len(raw) > max_frames:
        step = len(raw) / max_frames
        indices = [int(i * step) for i in range(max_frames)]
        raw = [raw[i] for i in indices]

    return [resize_with_alpha(f, size, bg) for f in raw]


def write_header(frames: list[Image.Image], out_path: Path, size: int,
                  key: tuple[int, int, int] | None = None,
                  key_tol: int = 20,
                  bg: tuple[int, int, int] = (0, 0, 0)) -> None:
    with out_path.open('w', encoding='ascii') as f:
        f.write('// Auto-generated by tools/gif_to_buffer.py.\n')
        f.write('// RGB565 animation frames for the thinking-loader.\n')
        f.write('#pragma once\n\n')
        f.write('#include <cstdint>\n\n')
        f.write(f'constexpr int kStarFrameW     = {size};\n')
        f.write(f'constexpr int kStarFrameH     = {size};\n')
        f.write(f'constexpr int kStarFrameCount = {len(frames)};\n\n')
        f.write('constexpr uint16_t kStarFrames'
                '[kStarFrameCount][kStarFrameW * kStarFrameH] = {\n')
        for fi, img in enumerate(frames):
            f.write(f'    // frame {fi}\n    {{\n')
            for y in range(size):
                row = []
                for x in range(size):
                    px = img.getpixel((x, y))
                    if isinstance(px, int):
                        r = g = b = px
                    else:
                        r, g, b = px[:3]
                    if key is not None and (
                        abs(r - key[0]) <= key_tol and
                        abs(g - key[1]) <= key_tol and
                        abs(b - key[2]) <= key_tol):
                        r, g, b = bg
                    row.append(f'0x{rgb_to_565(r, g, b):04X}')
                f.write('        ' + ','.join(row) + ',\n')
            f.write('    },\n')
        f.write('};\n')


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument('gif', type=Path, help='path to animated .gif')
    p.add_argument('--size',   type=int, default=40,
                   help='output W = H px')
    p.add_argument('--frames', type=int, default=12,
                   help='max frame count (downsamples evenly if more)')
    p.add_argument('--bg', default='0,0,0',
                   help='RGB background for transparent pixels, e.g. "0,0,0"')
    p.add_argument('--key-rgb', default=None,
                   help='RGB colour to treat as transparent (replaced with '
                        '--bg). Useful for GIFs without alpha but with a solid '
                        'background, e.g. "255,255,255" for white.')
    p.add_argument('--key-tol', type=int, default=20,
                   help='per-channel tolerance when matching --key-rgb')
    p.add_argument('--out',    type=Path,
                   default=Path(__file__).resolve().parents[1] / 'src' /
                           'claude_star_frames.h',
                   help='output header path')
    args = p.parse_args()

    bg = tuple(int(x) for x in args.bg.split(','))
    if len(bg) != 3:
        sys.exit('--bg must be three comma-separated ints, e.g. "0,0,0"')

    key = None
    if args.key_rgb:
        kparts = tuple(int(x) for x in args.key_rgb.split(','))
        if len(kparts) != 3:
            sys.exit('--key-rgb must be three comma-separated ints')
        key = kparts

    frames = load_frames(args.gif, args.size, args.frames, bg)
    write_header(frames, args.out, args.size, key=key,
                  key_tol=args.key_tol, bg=bg)

    bytes_per_frame = args.size * args.size * 2
    total = bytes_per_frame * len(frames)
    print(f'wrote {args.out}')
    print(f'  {len(frames)} frames × {args.size}×{args.size} RGB565 '
          f'= {total // 1024} KB in flash')


if __name__ == '__main__':
    main()
