#!/usr/bin/env python3
"""
slice_icons.py — slice the two gpt-image grid PNGs into 10 individual
40×40 RGB565 tool icons and emit a single C header.

Input layout:
  grid1.png  — 1024x1024, 2x4 grid (2 rows, 4 cols)
               Row 0: Bash, Edit, Read, Write
               Row 1: Grep, Glob, Task, WebFetch
  grid2.png  — 1024x1024, 1x2 grid (1 row, 2 cols)
               Col 0: Skill   Col 1: MCP

Output:
  firmware/src/tool_icons.h
"""

from pathlib import Path
from PIL import Image

GRID1 = '/Users/firshme/Desktop/work/cc_hud/gen_image/gpt_image_1779897224_1.png'
GRID2 = '/Users/firshme/Desktop/work/cc_hud/gen_image/gpt_image_1779897573_1.png'
OUT   = '/Users/firshme/Desktop/work/cc_hud/firmware/src/tool_icons.h'
PREVIEW = '/Users/firshme/Desktop/work/cc_hud/firmware/tools/icons_preview.png'

ICON_W = ICON_H = 40

# (label, (x, y, w, h) in source)
GRID1_CELLS = [
    ('Bash',      (   0,   0, 256, 512)),
    ('Edit',      ( 256,   0, 256, 512)),
    ('Read',      ( 512,   0, 256, 512)),
    ('Write',     ( 768,   0, 256, 512)),
    ('Grep',      (   0, 512, 256, 512)),
    ('Glob',      ( 256, 512, 256, 512)),
    ('Task',      ( 512, 512, 256, 512)),
    ('WebFetch',  ( 768, 512, 256, 512)),
]
GRID2_CELLS = [
    ('Skill', (   0, 0, 512, 1024)),
    ('MCP',   ( 512, 0, 512, 1024)),
]


def crop_center_square_and_resize(img: Image.Image, target: int) -> Image.Image:
    """LEGACY: crop the largest centred square out of img, resize to target.

    Kept for backward compatibility. New code should use
    crop_icon_bbox_and_resize() which auto-detects the orange icon bbox
    so we don't slice off the icon edges when the source cell aspect
    ratio doesn't match 1:1.
    """
    w, h = img.size
    s = min(w, h)
    x = (w - s) // 2
    y = (h - s) // 2
    sq = img.crop((x, y, x + s, y + s))
    return sq.resize((target, target), Image.LANCZOS)


def crop_icon_bbox_and_resize(cell: Image.Image, target: int,
                               pad_ratio: float = 0.10) -> Image.Image:
    """Find the orange icon bbox within `cell`, pad, square it, resize.

    Detects orange pixels (R high, R > G, R > B), takes their bbox,
    pads by `pad_ratio` of the bbox size, expands to a square, then
    resizes to target×target. Guarantees the icon is centred with
    consistent margin no matter where it sits inside the source cell.
    """
    rgb = cell.convert('RGB')
    px = rgb.load()
    w, h = rgb.size
    xs = []
    ys = []
    for y in range(0, h, 2):           # stride 2 — fast enough
        for x in range(0, w, 2):
            r, g, b = px[x, y]
            if r > 100 and r > g + 20 and r > b + 20:
                xs.append(x); ys.append(y)
    if not xs:
        # Fallback: legacy centred-square crop.
        return crop_center_square_and_resize(rgb, target)

    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    bw = x1 - x0 + 1
    bh = y1 - y0 + 1
    side = max(bw, bh)
    pad = int(side * pad_ratio)
    side_padded = side + 2 * pad
    cx = (x0 + x1) // 2
    cy = (y0 + y1) // 2
    # Square crop centred on icon bbox.
    half = side_padded // 2
    cx0 = max(0, cx - half)
    cy0 = max(0, cy - half)
    cx1 = min(w, cx0 + side_padded)
    cy1 = min(h, cy0 + side_padded)
    # Re-anchor if we hit the source edge so the result is still square.
    if cx1 - cx0 < side_padded:
        cx0 = max(0, cx1 - side_padded)
    if cy1 - cy0 < side_padded:
        cy0 = max(0, cy1 - side_padded)
    square = rgb.crop((cx0, cy0, cx1, cy1))
    return square.resize((target, target), Image.LANCZOS)


def rgb565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main():
    g1 = Image.open(GRID1).convert('RGB')
    g2 = Image.open(GRID2).convert('RGB')

    icons = []
    for label, (x, y, w, h) in GRID1_CELLS:
        cell = g1.crop((x, y, x + w, y + h))
        icon = crop_icon_bbox_and_resize(cell, ICON_W)
        icons.append((label, icon))

    for label, (x, y, w, h) in GRID2_CELLS:
        cell = g2.crop((x, y, x + w, y + h))
        icon = crop_icon_bbox_and_resize(cell, ICON_W)
        icons.append((label, icon))

    # Preview grid (scale icons up to 80×80 for human inspection)
    preview = Image.new('RGB', (80 * 5, 80 * 2), (30, 30, 30))
    for i, (label, ico) in enumerate(icons):
        big = ico.resize((80, 80), Image.NEAREST)
        preview.paste(big, ((i % 5) * 80, (i // 5) * 80))
    preview.save(PREVIEW)
    print(f'preview: {PREVIEW}')

    # Emit C header
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by tools/slice_icons.py.\n')
        f.write('// Tool icons (40x40 RGB565) + name→index mapping.\n')
        f.write('#pragma once\n\n')
        f.write('#include <cstdint>\n\n')
        f.write(f'constexpr int kIconW     = {ICON_W};\n')
        f.write(f'constexpr int kIconH     = {ICON_H};\n')
        f.write(f'constexpr int kIconCount = {len(icons)};\n\n')

        f.write('// Index labels (for cross-reference with kIconMap below).\n')
        for i, (label, _) in enumerate(icons):
            f.write(f'//   {i}: {label}\n')
        f.write('\n')

        f.write('constexpr uint16_t kIcons[kIconCount][kIconW * kIconH] = {\n')
        for i, (label, ico) in enumerate(icons):
            f.write(f'    // {i}: {label}\n    {{\n')
            for y in range(ICON_H):
                row = []
                for x in range(ICON_W):
                    r, g, b = ico.getpixel((x, y))
                    row.append(f'0x{rgb565(r, g, b):04X}')
                f.write('        ' + ','.join(row) + ',\n')
            f.write('    },\n')
        f.write('};\n\n')

        f.write(
            '// Tool-name → icon index. Use longest-prefix-match against\n'
            '// the incoming tool name; first matching entry wins. The\n'
            '// mcp__ catch-all is last so specific MCP servers can\n'
            '// override above it if we ever add more icons.\n'
            'struct IconMapping {\n'
            '    const char* prefix;\n'
            '    int8_t      icon_idx;\n'
            '};\n'
            'constexpr IconMapping kIconMap[] = {\n'
            '    {"Bash",          0},\n'
            '    {"Edit",          1},\n'
            '    {"MultiEdit",     1},\n'
            '    {"Read",          2},\n'
            '    {"Write",         3},\n'
            '    {"NotebookEdit",  3},\n'
            '    {"Grep",          4},\n'
            '    {"Glob",          5},\n'
            '    {"Task",          6},\n'
            '    {"TaskCreate",    6},\n'
            '    {"TaskUpdate",    6},\n'
            '    {"WebFetch",      7},\n'
            '    {"WebSearch",     7},\n'
            '    {"Skill",         8},\n'
            '    {"ToolSearch",    8},\n'
            '    {"mcp__",         9},\n'
            '};\n'
            'constexpr int kIconMapLen = sizeof(kIconMap) / sizeof(kIconMap[0]);\n'
        )

    print(f'wrote {OUT}')
    print(f'  {len(icons)} icons × {ICON_W}×{ICON_H} RGB565 '
          f'= {len(icons) * ICON_W * ICON_H * 2 // 1024} KB in flash')


if __name__ == '__main__':
    main()
